### ISSUE TITLE
[iOS] React-native-cli example duplicate resources issue

### ISSUE THREAD

**Issue by fdobre** [flagship-io/flagship-react-native-sdk#60]
Steps to replicate:

install example deps and attempt to build:

![Screenshot 2023-01-30 at 12 15 51](https://user-images.githubusercontent.com/3833179/215450619-c29a62d2-426c-45d6-8629-1a4d1bf392ef.png)

Go to Xcode -> target Build settings -> Copy bundle resources -> observe the duplicates from the above print screen

**Comment by Heihokon** [comment]
Thanks you're welcome
