### ISSUE TITLE
[iOS] React-native-cli example build error

### ISSUE THREAD

**Issue by fdobre** [flagship-io/flagship-react-native-sdk#61]
Steps: 

1. Install dependencies for react-native-cli example
2. Run `npx react-native run-ios --simulator="iPhone 14"`

```
ios/reactnativeqa/AppDelegate.m:52:49: no visible @interface for 'RCTBundleURLProvider' declares the selector 'jsBundleURLForBundleRoot:fallbackResource:'

  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
```

**Comment by Heihokon** [comment]
Hello @fdobre, Please use this example [https://github.com/flagship-io/flagship-react-native-sdk/tree/master/qa-app](https://github.com/flagship-io/flagship-react-native-sdk/tree/master/qa-app) instead

**Comment by fdobre** [comment]
@Heihokon  Thank you, the rn-cli example uses `"@flagship.io/react-native-sdk": "^2.1.6-alpha.1",`. The one from the link you provided uses `"^3.0.1",` ! That is very helpful!

**Comment by Heihokon** [comment]
Thanks you're welcome
