### ISSUE TITLE
 Property 'Intl' doesn't exist error 

### ISSUE THREAD

**Issue by fdobre** [flagship-io/flagship-react-native-sdk#72]
Property 'Intl' doesn't exist error 

SDK version: 3.3.1 and 3.2.4

![Screenshot 2024-02-12 at 11 14 30](https://github.com/flagship-io/flagship-react-native-sdk/assets/3833179/092b76b5-c14d-4a1a-9b0d-f8752bb91f13)

What would be latest versions of the SDK that doesn't trigger this error and that has a stable enableClientCache feature?

Any insights on this will be greatly appreciated.

**Comment by Madi-Ji** [comment]
Hey @fdobre, 

Thanks for opening this issue, our SDK Team is on it !
They'll be back to you later today with an update regarding the situation & your question above.

In the meantime, have a lovely day

**Comment by Madi-Ji** [comment]
I've got some news @fdobre,

During the night,
we've released a [Beta version](https://www.npmjs.com/package/@flagship.io/react-native-sdk/v/3.3.2-beta.0?activeTab=versions) of the `3.3.2`
Should fix the issue you've experienced, but we'll need to confirm before going stable.
Would you be able to try `3.3.2-beta.0` and get back to us 😃?

**Comment by fdobre** [comment]
Hey @Madi-Ji! Thank you for the fast response! I will take a look in a few hours and come back to you!

**Comment by fdobre** [comment]
@Madi-Ji I can still replicate the issue in 3.3.2-beta-0:
![Screenshot 2024-02-13 at 14 09 33](https://github.com/flagship-io/flagship-react-native-sdk/assets/3833179/e3c73134-4bd4-4cf0-8d33-35849ddfd72e)

**Comment by Madi-Ji** [comment]
There we go,
we should have been able to reproduce the issue and, hopefully, a new release should fix it.

@fdobre, [`3.3.2-beta.1`](https://www.npmjs.com/package/@flagship.io/react-native-sdk/v/3.3.2-beta.1) released,
same as before, if you could try 🙏  this version, would be very useful !
Thanks for your time & efforts

**Comment by fdobre** [comment]
@Madi-Ji Issue looks fixed in 3.2.2-beta.1:
![Screenshot 2024-02-13 at 22 28 41](https://github.com/flagship-io/flagship-react-native-sdk/assets/3833179/b5f50caf-c998-47b1-8fd0-58dcb5b21d24)

**Comment by fdobre** [comment]
@Madi-Ji Is it OK if we'll use the enableClientCache feature or should we manually try to create such a feature?

**Comment by Madi-Ji** [comment]
Hey @fdobre,

Yeah, it works !
Now, we can go for a full release.
I'll close this issue (#72) upon the release of the `v3.3.2` (stable)

--
About your topic around `enableClientCache`, try the default behaviour of the SDK and use its embedded logic.
If it doesn't behave as you except, your TSM will be able to help to use the [`IVisitorCacheImplementation` interface](https://docs.developers.flagship.io/docs/react-native-v3-3-x#visitor-cache) (advance storage method)

Cheers,
Julien

**Comment by Madi-Ji** [comment]
This Issue was fixed in v3.3.2

Stable version released : 
- [NPM](https://www.npmjs.com/package/@flagship.io/react-native-sdk/v/3.3.2?activeTab=versions)
- [Github Release](https://github.com/flagship-io/flagship-react-native-sdk/releases/tag/3.3.2) Tag 3.3.2 & Release Note
- [Official documentation](https://docs.developers.flagship.io/docs/react-native-sdk#release-notes)

Closing this issue ✅
